### ISSUE TITLE
The accepted format for SAML ID is not well documented

### ISSUE THREAD

**Issue by fumieval** [MicrosoftDocs/SupportArticles-docs#763] opened 2022-10-24 05:21 UTC
We saw a confusing error message on AzureAD, alluding that the given SAML ID is invalid because it begins with an ASCII digit (which is not). I got the identical error message when I shortened the ID to 20 characters.

The problem seemed to go away when I changed the format to hexadecimal prefixed by "id", but I'm not confident because the accepted format is not documented thoroughly.

```
AADSTS7500529: The value 'p0hxHdKbylFDd2/hzGyKUTiliWBzh72PxznHR50adRl+vml9mNDJu26F3sSHDGGrRU0O7+lXqOz7p/WvtA94gQ==' is not a valid SAML ID. The ID must not begin with a number.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffb44f0f-e3d3-459e-2f11-10a7fd8958a4
* Version Independent ID: 8a827dba-0353-4b88-bfd1-1edb6dfbf97d
* Content: [Error AADSTS75005 - The request is not a valid Saml2 protocol message - Active Directory](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts75005-not-a-valid-saml-request)
* Content Source: [support/azure/active-directory/error-code-AADSTS75005-not-a-valid-saml-request.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/active-directory/error-code-AADSTS75005-not-a-valid-saml-request.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment] 2022-10-25 07:23
@fumieval, Thanks for the feedback. I will forward this issue to our product team.

**Comment by genlin** [comment] 2022-11-02 01:06
Close this issue since the PR is merged.

**Comment by omondiatieno** [comment] 2022-11-24 14:54
#reassign:AllisonAm

**Comment by genlin** [comment] 2022-12-15 08:04
Close the issue since the problem is fixed

**Closed by genlin** 2022-12-15 08:04 UTC
Labels: TriageNeeded, active-directory/svc, Pri2, app-mgmt/subsvc

**Comment by fumieval** [comment] 2022-12-15 10:14
Thank you!
