### ISSUE TITLE
KMS IP Address in the Notes is incorrect.

### ISSUE THREAD

**Issue by lezoid** [MicrosoftDocs/SupportArticles-docs#787] opened 2022-11-18 05:40 UTC
https://learn.microsoft.com/ja-jp/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation#solution

notes on the Japanese(ja-jp) version of the page, the IP address of KMS seems to be incorrect.

× ：20.118.99.244
〇：20.118.99.224

Please let me know if I am sending the Issue to the wrong project.

JA-JP Version)
注意 *ネットワークセキュリティグループに関連する問題を軽減するために、azkms.core.windows.netはkms.core.windows.netを今のところ指します。 問題が解決した後（2022年10月3日を予定）、azkms.core.windows.netは 2 つの新しいIPアドレス、20.118.99.244および40.83.235.53を指し示します。

ex. EN-US Version)
Note * To mitigate an issue related to Network Security Group, azkms.core.windows.net points to kms.core.windows.net for now. After the issue is resolved (planned for October 3rd, 2022) azkms.core.windows.net will point to two new IP addresses: 20.118.99.224 and 40.83.235.53.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35f3cda3-0175-ff45-6933-cafb8badd13c
* Version Independent ID: a316db39-073a-72db-a9a1-cd34ca6ed9b3
* Content: [Use Azure custom routes to enable KMS activation with forced tunneling - Virtual Machines](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/custom-routes-enable-kms-activation#solution)
* Content Source: [support/azure/virtual-machines/custom-routes-enable-kms-activation.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/custom-routes-enable-kms-activation.md)
* Service: **virtual-machines**
* Sub-service: **vm-windows-activation**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment] 2022-11-21 01:27
@lezoid, Thanks for the feedback. I will fix the translation issue.

**Comment by genlin** [comment] 2022-12-15 08:03
Close the issue since the issue is fixed.

**Closed by genlin** 2022-12-15 08:03 UTC
Labels: virtual-machines/svc, Pri2, vm-windows-activation/subsvc
