### ISSUE TITLE
The Korean page is missing some comments from English page.

### ISSUE THREAD

**Issue by Yongchool** [MicrosoftDocs/SupportArticles-docs#563] opened 2022-05-12 06:54 UTC
[Enter feedback here]

Hello,

In English page have "This is a known issue and we currently do not have an ETA for a fix." comments as the below capture.
![image](https://user-images.githubusercontent.com/67408348/168008785-fcfe1c10-97cc-4b8e-9fe1-f254a64b3f3c.png)

But in Korean page have different comments with English page as "This is a known issue and we currently have an ETA for a fix."
The Korean comments is missing "do not have", it is very import missing, please fix it.

![image](https://user-images.githubusercontent.com/67408348/168009176-79d23730-8a76-47a2-b8bc-cc9fe32a1ce4.png)

Thank you,
Best Regards
Yongchool Kim.

![screen capture](https://user-images.githubusercontent.com/67408348/168009720-deac626b-9859-4ef3-a452-d516210431d3.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aaf964f-63b8-c007-9724-4ab800df54a6
* Version Independent ID: 6cbdb843-b282-0cf3-ea99-153dab004ac1
* Content: [Support for 32-bit operating systems in Azure virtual machines - Virtual Machines](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/support-32-bit-operating-systems-virtual-machines#feedback)
* Content Source: [support/azure/virtual-machines/support-32-bit-operating-systems-virtual-machines.md](https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/azure/virtual-machines/support-32-bit-operating-systems-virtual-machines.md)
* Service: **virtual-machines**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by genlin** [comment] 2022-05-17 02:56
@Yongchool, Thanks for the feedback. I will forward this problem to our localization team.

**Comment by genlin** [comment] 2022-11-29 05:06
Close the issue since the problem is fixed.

**Closed by genlin** 2022-11-29 05:06 UTC
Labels: virtual-machines/svc, Pri2
